import type { MapSettings, Zone, Edge, CatalogItem, ContentLimitEntry, ContentPoolBan, ContentPoolGroup, ZoneObject, Preset, CustomObjectList, CustomObjectListEntry, TerrainProfile } from '../types/editor';
import type {
  JsonObject,
  JsonValue,
  RmgBorder,
  RmgConnection,
  RmgContentCountLimit,
  RmgContentList,
  RmgContentListEntry,
  RmgContentPool,
  RmgContentPoolGroup,
  RmgGlobalBans,
  RmgPassageConnection,
  RmgMainObject,
  RmgMandatoryObject,
  RmgOrientation,
  RmgPlacementRule,
  RmgProximityConnection,
  RmgTemplate,
  RmgVariant,
  RmgWinConditions,
  RmgZone,
  RmgZoneLayout
} from '../types/rmg';
import { safeName, biomeIds, zoneTypes, catalogItemForReference } from '../store/useEditorStore';
import { resolveDistance, ruleBounds } from '../store/constants';
import { defaultTerrainProfiles, isBuiltInProfileName, isBuiltInLimitName } from '../store/constants';

const defaultTemplateDescription = "Generated by Olden Era RMG Visual Template Editor.";

function orientationAnchorName(settings: MapSettings, zones: Zone[]): string {
  return zones.some((zone) => zone.id === settings.orientationAnchor)
    ? settings.orientationAnchor
    : (zones.find((zone) => zone.type === "spawn")?.id || zones[0]?.id || "");
}

function connectionName(edgeData: Edge): string {
  return edgeData.id;
}

function getBaseType(zoneType: string, presets: Record<string, Preset>): string {
  const preset = presets[zoneType];
  return preset ? preset.baseType : zoneType;
}

function poolName(type: string, presets: Record<string, Preset>, guarded: boolean, zone?: Zone): string {
  const suffix = guarded ? "guarded" : "unguarded";
  const baseType = getBaseType(type, presets);
  const hasSpawn = baseType === "spawn" || (zone?.mainObjects && zone.mainObjects.some(mo => mo.type === "Spawn"));
  if (hasSpawn) return `visual_pool_${suffix}_start`;
  if (baseType === "low") return `visual_pool_${suffix}_low`;
  if (baseType === "medium") return `visual_pool_${suffix}_medium`;
  if (baseType === "high") return `visual_pool_${suffix}_high`;
  return `visual_pool_${suffix}_low`;
}

/**
 * Builds a biome rule from explicit mode parts. Shared by the content/meta
 * biome export and (for round-trip classification) the importer.
 */
export function auxBiomeRule(mode: 'own' | 'random' | 'spawn' | 'specific', source?: string, id?: string) {
  if (mode === 'own') return { type: 'MatchMainObject' as const, args: ['0'] };
  if (mode === 'spawn' && source) return { type: 'MatchZone' as const, args: [source] };
  if (mode === 'specific' && id && biomeIds.includes(id)) return { type: 'FromList' as const, args: [id] };
  return { type: 'FromList' as const, args: [] };
}

function biomeRule(zone: Zone, presets: Record<string, Preset>) {
  const baseType = getBaseType(zone.type, presets);
  const hasOwnBiome = baseType === "spawn" || (zone.mainObjects && zone.mainObjects.length > 0);
  if (zone.biomeMode === "own" && hasOwnBiome) {
    return { type: "MatchMainObject" as const, args: ["0"] };
  }
  if (zone.biomeMode === "spawn" && zone.biomeSource) {
    return { type: "MatchZone" as const, args: [zone.biomeSource] };
  }
  if (zone.biomeMode === "specific" && biomeIds.includes(zone.biomeId)) {
    return { type: "FromList" as const, args: [zone.biomeId] };
  }
  return { type: "FromList" as const, args: [] };
}

function editorBiomeFromRule(rule: unknown): {
  mode: Zone["biomeMode"];
  source: string;
  id: string;
} {
  if (!rule || typeof rule !== "object") {
    return { mode: "random", source: "", id: "Grass" };
  }

  const biomeRule = rule as { type?: unknown; args?: unknown };
  const args = Array.isArray(biomeRule.args) ? biomeRule.args : [];
  const firstArgument = typeof args[0] === "string" ? args[0] : "";

  if (biomeRule.type === "MatchMainObject") {
    return { mode: "own", source: "", id: "Grass" };
  }
  if (biomeRule.type === "MatchZone" && firstArgument) {
    return { mode: "spawn", source: firstArgument, id: "Grass" };
  }
  if (biomeRule.type === "FromList" && firstArgument) {
    return { mode: "specific", source: "", id: firstArgument };
  }
  return { mode: "random", source: "", id: "Grass" };
}

function isImportedBiomeUnchanged(zone: Zone): boolean {
  if (!zone.originalZoneBiome) return false;
  const original = editorBiomeFromRule(zone.originalZoneBiome);
  return (
    zone.biomeMode === original.mode &&
    zone.biomeSource === original.source &&
    zone.biomeId === original.id
  );
}


function boundsMatchRule(
  bounds: { min: number; max: number } | null,
  rule: RmgPlacementRule | null
): boolean {
  const rb = rule ? ruleBounds(rule) : null;
  // "any" matches the absence of that rule type, or a rule we can't express as
  // a min/max distance (it then rides through verbatim, e.g. `target`-only).
  if (!bounds) return !rb;
  if (!rb) return false;
  return rb.min === bounds.min && rb.max === bounds.max;
}

function buildObjectPlacementRules(zone: Zone, entry: ZoneObject): RmgPlacementRule[] {
  const roadBounds = resolveDistance(entry.roadDistance);
  const townBounds = resolveDistance(entry.townDistance);

  // Keep the original rules verbatim while the model's distances still match
  // them (the user hasn't touched the Road/Town distance) — this preserves
  // exact values, weights, args and rule types the distance model can't hold.
  if (Array.isArray(entry.rawRules)) {
    let roadRule: RmgPlacementRule | null = null;
    let townRule: RmgPlacementRule | null = null;
    for (const rule of entry.rawRules) {
      if (rule.type === "Road") roadRule = rule;
      else if (rule.type === "MainObject") townRule = rule;
    }
    if (boundsMatchRule(roadBounds, roadRule) && boundsMatchRule(townBounds, townRule)) {
      return entry.rawRules.map((rule) => ({ ...rule }));
    }
  }

  const rules: RmgPlacementRule[] = [];
  const hasTown = (zone.mainObjects || []).length > 0;
  if (roadBounds) {
    rules.push({ type: "Road", args: [], targetMin: roadBounds.min, targetMax: roadBounds.max, weight: 1 });
  }
  if (hasTown && townBounds) {
    rules.push({ type: "MainObject", args: ["0"], targetMin: townBounds.min, targetMax: townBounds.max, weight: 1 });
  }
  return rules;
}

function toMandatoryObject(
  zone: Zone,
  entry: ZoneObject,
  index: number,
  useEntryName = false
): RmgMandatoryObject {
  const base: RmgMandatoryObject = {
    name: useEntryName && entry.name
      ? entry.name
      : `name_${safeName(zone.id).toLowerCase()}_${index + 1}_${safeName(entry.id).toLowerCase()}`
  };
  if (entry.kind === "list" && (entry.rawIncludeLists?.length || entry.includeList)) {
    // Preserve the full set of content lists when the object referenced several.
    base.includeLists = entry.rawIncludeLists?.length ? [...entry.rawIncludeLists] : [entry.includeList!];
  } else if (entry.sid) {
    base.sid = entry.sid;
  }
  if (entry.variant !== null && entry.variant !== undefined && Number.isFinite(Number(entry.variant))) {
    base.variant = Math.trunc(Number(entry.variant));
  }
  if (entry.isMine) base.isMine = true;
  if (entry.owner) base.owner = `Player${entry.owner}`;
  if (entry.designatedEncounter !== undefined) base.designatedEncounter = entry.designatedEncounter;
  if (entry.nestedContent?.length) base.content = entry.nestedContent.map((c) => ({ sid: c.sid, weight: c.weight }));
  // Tri-state: omit isGuarded entirely when unset, so the engine applies its
  // own default instead of being pinned to false.
  if (entry.guarded !== undefined) base.isGuarded = entry.guarded;
  base.soloEncounter = Boolean(entry.soloEncounter);
  const rules = buildObjectPlacementRules(zone, entry);
  if (rules.length) base.rules = rules;
  return base;
}

function buildMandatoryObjects(zone: Zone): RmgMandatoryObject[] {
  const content: RmgMandatoryObject[] = [];
  for (const entry of zone.objects) {
    const count = Math.max(1, Math.min(99, Math.trunc(Number(entry.count) || 1)));
    for (let copy = 0; copy < count; copy += 1) {
      // A user-set name identifies one specific entry, so only the first copy
      // carries it; the rest fall back to auto-generated names.
      content.push(toMandatoryObject(zone, entry, content.length, copy === 0));
    }
  }
  return content;
}

function contentPool(
  name: string,
  priceBounds: number[],
  weights: number[],
  groups: RmgContentPoolGroup[],
  bans: Array<{ sid: string }>
): RmgContentPool {
  return {
    name,
    valueDistribution: { priceBounds, weights },
    groups: groups.filter((poolGroup) => poolGroup.includeLists.length),
    bans
  };
}

function group(objectLibrary: CatalogItem[], weight: number, includeLists: string[]) {
  const availableLists = objectLibrary.length
    ? includeLists.filter((name) => catalogItemForReference(objectLibrary, { kind: "list", value: name }))
    : includeLists;
  return { weight, includeLists: availableLists };
}

function buildContentPools(zones: Zone[], objectLibrary: CatalogItem[], presets: Record<string, Preset>, extraReferencedNames?: Set<string>): RmgContentPool[] {
  const bans = [{ sid: "mirage" }, { sid: "pandora_box" }, { sid: "scroll_box" }, { sid: "enchanted_scroll_box" }, { sid: "mythic_scroll_box" }];
  const pools = [
    contentPool("visual_pool_guarded_start", [3999, 6999, 12999], [8, 12, 8, 0], [
      group(objectLibrary, 18000, ["visual_editor_common_artifacts_no_scrolls"]),
      group(objectLibrary, 9000, ["visual_editor_rare_artifacts_no_scrolls"]),
      group(objectLibrary, 16000, ["basic_content_list_building_hero_stats_and_skills_tier_1"]),
      group(objectLibrary, 14000, ["basic_content_list_building_hero_exp_tier_1"]),
      group(objectLibrary, 14000, ["basic_content_list_building_magic_tier_1"]),
      group(objectLibrary, 16000, ["basic_content_list_building_resource_banks_tier_1"]),
      group(objectLibrary, 14000, ["basic_content_list_building_guarded_resource_banks_tier_1"])
    ], bans),
    contentPool("visual_pool_unguarded_start", [3999, 6999], [8, 14, 6], [
      group(objectLibrary, 12000, ["basic_content_list_basic_storage"]),
      group(objectLibrary, 14000, ["basic_content_list_building_hero_exp_tier_1"]),
      group(objectLibrary, 18000, ["basic_content_list_building_resource_banks_tier_1"])
    ], bans),
    contentPool("visual_pool_guarded_low", [3999, 6999, 12999], [5, 12, 14, 2], [
      group(objectLibrary, 16000, ["visual_editor_common_artifacts_no_scrolls"]),
      group(objectLibrary, 12000, ["visual_editor_rare_artifacts_no_scrolls"]),
      group(objectLibrary, 18000, ["basic_content_list_building_hero_stats_and_skills_tier_1"]),
      group(objectLibrary, 16000, ["basic_content_list_building_hero_exp_tier_1"]),
      group(objectLibrary, 18000, ["basic_content_list_building_magic_tier_1"]),
      group(objectLibrary, 22000, ["basic_content_list_building_guarded_resource_banks_tier_1"])
    ], bans),
    contentPool("visual_pool_unguarded_low", [3999, 6999, 12999], [6, 12, 8, 1], [
      group(objectLibrary, 12000, ["basic_content_list_basic_storage"]),
      group(objectLibrary, 18000, ["basic_content_list_building_resource_banks_tier_1"]),
      group(objectLibrary, 10000, ["basic_content_list_building_hero_exp_tier_1"])
    ], bans),
    contentPool("visual_pool_guarded_medium", [6999, 12999, 22599], [4, 12, 16, 4], [
      group(objectLibrary, 16000, ["visual_editor_rare_artifacts_no_scrolls"]),
      group(objectLibrary, 12000, ["visual_editor_epic_artifacts_no_scrolls"]),
      group(objectLibrary, 18000, ["basic_content_list_building_hero_exp_tier_2"]),
      group(objectLibrary, 16000, ["basic_content_list_building_hero_stats_and_skills_tier_2"]),
      group(objectLibrary, 14000, ["basic_content_list_building_magic_tier_2"]),
      group(objectLibrary, 12000, ["basic_content_list_building_uncommon_interact"]),
      group(objectLibrary, 30000, ["basic_content_list_building_guarded_resource_banks_tier_2_no_biome_restriction"])
    ], bans),
    contentPool("visual_pool_unguarded_medium", [3999, 6999, 12999], [4, 10, 12, 3], [
      group(objectLibrary, 10000, ["basic_content_list_basic_storage"]),
      group(objectLibrary, 10000, ["basic_content_list_building_hero_exp_tier_2"]),
      group(objectLibrary, 18000, ["basic_content_list_building_resource_banks_tier_2"])
    ], bans),
    contentPool("visual_pool_guarded_high", [12999, 22599, 39999], [2, 8, 18, 8], [
      group(objectLibrary, 18000, ["visual_editor_epic_artifacts_no_scrolls"]),
      group(objectLibrary, 12000, ["visual_editor_legendary_artifacts_no_scrolls"]),
      group(objectLibrary, 18000, ["basic_content_list_building_hero_stats_and_skills_tier_3"]),
      group(objectLibrary, 14000, ["basic_content_list_building_hero_exp_tier_2"]),
      group(objectLibrary, 8000, ["basic_content_list_building_epic_interact"]),
      group(objectLibrary, 34000, ["basic_content_list_building_guarded_resource_banks_tier_3"])
    ], bans),
    contentPool("visual_pool_unguarded_high", [3999, 6999, 12999], [3, 8, 10, 2], [
      group(objectLibrary, 10000, ["basic_content_list_basic_storage"]),
      group(objectLibrary, 12000, ["basic_content_list_building_hero_exp_tier_2"]),
      group(objectLibrary, 14000, ["basic_content_list_building_resource_banks_tier_2"])
    ], bans)
  ];
  
  const usedNames = new Set<string>(extraReferencedNames ?? []);
  for (const zone of zones) {
    usedNames.add(poolName(zone.type, presets, true, zone));
    usedNames.add(poolName(zone.type, presets, false, zone));
  }
  return pools.filter((pool) => usedNames.has(pool.name));
}

function requiredGeneratedContentLists(zones: Zone[], contentPools: RmgContentPool[]): Set<string> {
  const names = new Set<string>();
  for (const zone of zones) {
    for (const object of zone.objects) {
      if (object.includeList?.startsWith("visual_editor_")) {
        names.add(object.includeList);
      }
    }
  }
  for (const pool of contentPools) {
    for (const poolGroup of pool.groups || []) {
      for (const name of poolGroup.includeLists || []) {
        if (name.startsWith("visual_editor_")) {
          names.add(name);
        }
      }
    }
  }
  return names;
}

function buildContentLists(
  artifactLists: Record<string, RmgContentListEntry[]>,
  requiredNames = new Set<string>()
): RmgContentList[] {
  return Object.entries(artifactLists)
    .filter(([name]) => requiredNames.has(name))
    .map(([name, ids]) => ({
      name,
      content: ids
    }));
}

function defaultBorder(): RmgBorder {
  return {
    cornerRadius: 0,
    obstaclesWidth: 3,
    obstaclesNoise: [{ amp: 1, freq: 12 }],
    waterWidth: 0,
    waterNoise: [{ amp: 1, freq: 12 }],
    waterType: "water grass"
  };
}

function profileToRmgLayout(profile: TerrainProfile): RmgZoneLayout {
  const layout: RmgZoneLayout = { name: profile.name };
  if (profile.obstaclesFill !== undefined) layout.obstaclesFill = profile.obstaclesFill;
  if (profile.obstaclesFillVoid !== undefined) layout.obstaclesFillVoid = profile.obstaclesFillVoid;
  if (profile.lakesFill !== undefined) layout.lakesFill = profile.lakesFill;
  if (profile.minLakeArea !== undefined) layout.minLakeArea = profile.minLakeArea;
  if (profile.elevationClusterScale !== undefined) layout.elevationClusterScale = profile.elevationClusterScale;
  if (profile.elevationModes !== undefined) {
    layout.elevationModes = profile.elevationModes.map((mode) => ({ ...mode }));
  }
  if (profile.roadClusterArea !== undefined) layout.roadClusterArea = profile.roadClusterArea;
  return { ...layout, ...(profile.rawFields || {}) };
}

function defaultZoneLayouts(zones: Zone[], presets: Record<string, Preset>, settings: MapSettings): RmgZoneLayout[] {
  // Profiles referenced by a zone — explicitly or through the type-based
  // "Auto" resolution — are always emitted. Beyond that, only the template's
  // own profiles go out verbatim (official templates ship a few unused ones);
  // the editor's built-ins and the user's custom library stay private.
  const referencedNames = new Set(zones.map((zone) => {
    const baseType = getBaseType(zone.type, presets);
    return zone.layout || zoneTypes[baseType]?.layout || zoneTypes.neutral.layout;
  }));
  const result = (settings.terrainProfiles || [])
    .filter((profile) =>
      referencedNames.has(profile.name) ||
      (!profile.custom && !isBuiltInProfileName(profile.name))
    )
    .map(profileToRmgLayout);

  // Safety net: zones may reference one of the editor's type-default layout
  // names that is not among the template's profiles (e.g. a zone added to an
  // imported template) — append the default profile so the game finds it.
  const fallbacks = defaultTerrainProfiles().map(profileToRmgLayout);
  zones.forEach((zone) => {
    const baseType = getBaseType(zone.type, presets);
    const layoutName = zone.layout || zoneTypes[baseType]?.layout || zoneTypes.neutral.layout;
    if (!result.some(l => l.name === layoutName)) {
      const fallback = fallbacks.find(l => l.name === layoutName);
      if (fallback) result.push(fallback);
    }
  });

  return result;
}

function toRmgZone(zone: Zone, edges: Edge[], presets: Record<string, Preset>, settings: MapSettings): RmgZone {
  const relatedEdges = edges.filter((edgeData) => 
    (edgeData.from === zone.id || edgeData.to === zone.id) && 
    edgeData.connectionType !== 'Proximity'
  );
  const baseType = getBaseType(zone.type, presets);
  const hasSpawn = baseType === "spawn" || (zone.mainObjects && zone.mainObjects.some(mo => mo.type === "Spawn"));
  
  // Use original layout if present
  const layout = zone.layout || zoneTypes[baseType]?.layout || (hasSpawn ? "visual_editor_layout_spawn" : "visual_editor_layout_neutral");
  
  const contentCountLimits = zone.contentCountLimits ?? [hasSpawn ? "content_limits_spawn" : "content_limits_side"];
  const guardedContentPool = zone.guardedContentPool ?? [poolName(zone.type, presets, true, zone)];
  const unguardedContentPool = zone.unguardedContentPool ?? [poolName(zone.type, presets, false, zone)];
  const resourcesContentPool = zone.resourcesContentPool ?? [hasSpawn ? "content_pool_general_resources_start_zone_poor" : "content_pool_general_resources_side_zone_poor"];

  const generatedBiome = biomeRule(zone, presets);
  const isBiomeUnchanged = isImportedBiomeUnchanged(zone);

  const zoneBiome = isBiomeUnchanged ? zone.originalZoneBiome : generatedBiome;
  // Content/meta biomes: an explicit mode builds its own rule; 'land' (the
  // default) follows the ground, preserving the imported original verbatim
  // while the ground biome is untouched.
  const auxBiome = (
    mode: Zone['contentBiomeMode'],
    source: string | undefined,
    id: string | undefined,
    original: Zone['originalContentBiome']
  ) => {
    if (mode && mode !== 'land') return auxBiomeRule(mode, source, id);
    return isBiomeUnchanged ? (original || zoneBiome) : generatedBiome;
  };
  const contentBiome = auxBiome(zone.contentBiomeMode, zone.contentBiomeSource, zone.contentBiomeId, zone.originalContentBiome);
  const metaObjectsBiome = auxBiome(zone.metaBiomeMode, zone.metaBiomeSource, zone.metaBiomeId, zone.originalMetaObjectsBiome);

  const rmgZone: RmgZone = {
    ...(zone.rawFields || {}),
    name: zone.id,
    size: Number(zone.size) || 1,
    layout,
    guardCutoffValue: zone.guardCutoffValue ?? 1500,
    guardRandomization: zone.guardRandomization ?? 0.25,
    guardWeeklyIncrement: zone.guardWeeklyIncrement ?? 0.15,
    guardReactionDistribution: zone.guardReactionDistribution || [60, 20, 10, 10, 2, 0],
    contentCountLimits,
    guardedContentPool,
    unguardedContentPool,
    resourcesContentPool,
    guardedContentValue: Number(zone.guardedValue) || 0,
    unguardedContentValue: Number(zone.unguardedValue) || 0,
    resourcesValue: Number(zone.resourcesValue) || 0,
    mandatoryContent: zone.mandatoryContent || [`mandatory_content_${safeName(zone.id).toLowerCase()}`],
    zoneBiome,
    contentBiome,
    metaObjectsBiome,
    crossroadsPosition: zone.rawFields?.crossroadsPosition ?? 0
  };

  // Optional in the game format: emitted only when set so imported zones that
  // omit them keep the game defaults (new editor zones set them explicitly).
  if (zone.guardMultiplier !== undefined) rmgZone.guardMultiplier = zone.guardMultiplier;
  if (zone.randomHireInitialUnitIncrement !== undefined) rmgZone.randomHireInitialUnitIncrement = [...zone.randomHireInitialUnitIncrement];
  if (zone.randomHireEnableWeeklyUnitIncrement !== undefined) rmgZone.randomHireEnableWeeklyUnitIncrement = [...zone.randomHireEnableWeeklyUnitIncrement];
  if (zone.diplomacyModifier !== undefined) rmgZone.diplomacyModifier = zone.diplomacyModifier;
  if (zone.encounterHolesSettings !== undefined) rmgZone.encounterHolesSettings = { ...zone.encounterHolesSettings };
  if (zone.guardedValuePerArea !== undefined) rmgZone.guardedContentValuePerArea = zone.guardedValuePerArea;
  if (zone.unguardedValuePerArea !== undefined) rmgZone.unguardedContentValuePerArea = zone.unguardedValuePerArea;
  if (zone.resourcesValuePerArea !== undefined) rmgZone.resourcesValuePerArea = zone.resourcesValuePerArea;

  type RoadSegment = NonNullable<Zone['roads']>[number];
  const connectionOf = (segment: RoadSegment): string | undefined =>
    [segment.from, segment.to].find((term) => term?.type === 'Connection')?.args?.[0];
  const crossroadsRoad = (edgeData: Edge): RoadSegment => ({
    type: edgeData.roadType ?? "Stone",
    from: { type: "Crossroads" },
    to: { type: "Connection", args: [connectionName(edgeData)] }
  });

  // Reconcile passthrough roads with the current graph: keep internal roads and
  // roads to still-existing connections (rewriting the Stone/Dirt surface), drop
  // roads to connections the user deleted, and add a road for every new
  // connection that has none yet — so recreated/added connections stay consistent.
  const originalConnectionIds = new Set(settings.originalConnectionIds ?? []);
  const reconcileRoads = (baseRoads: RoadSegment[]): RoadSegment[] => {
    const kept = baseRoads
      .filter((segment) => {
        const ref = connectionOf(segment);
        if (ref === undefined || edges.some((candidate) => candidate.id === ref)) return true;
        // Ref points to a missing connection: drop only if it was an imported
        // connection the user deleted; keep a template's own dangling roads.
        return !originalConnectionIds.has(ref);
      })
      .map((segment) => {
        const ref = connectionOf(segment);
        const edgeData = ref ? edges.find((candidate) => candidate.id === ref) : undefined;
        return edgeData?.roadType && segment.type !== edgeData.roadType
          ? { ...segment, type: edgeData.roadType }
          : segment;
      });
    const covered = new Set(kept.map(connectionOf).filter((id): id is string => Boolean(id)));
    const added = relatedEdges
      .filter((edgeData) => !edgeData.imported && !covered.has(edgeData.id))
      .map(crossroadsRoad);
    return [...kept, ...added];
  };

  if (zone.roads !== undefined) {
    rmgZone.roads = reconcileRoads(zone.roads);
  } else if (!zone.importedObjects) {
    // Editor-created zone: a crossroads road for each of its connections.
    rmgZone.roads = relatedEdges.map(crossroadsRoad);
  } else {
    // Imported zone that had no roads of its own — still wire up new connections.
    const reconciled = reconcileRoads([]);
    if (reconciled.length) rmgZone.roads = reconciled;
  }
  
  const rmgMainObjects = (zone.mainObjects || []).map((obj) => {
    const isVictoryCity = settings.cityHoldEnabled && zone.id === settings.victoryCityZoneId && obj.holdCityWinCon;
    
    // Merge with rawFields to preserve unrecognized keys
    const baseObj: RmgMainObject = {
      ...(obj.rawFields || {}),
      type: obj.type
    };

    // Guard fields live on the model and are emitted only when set, so
    // imported objects that omit them keep the game defaults (new editor
    // objects get explicit defaults at creation time).
    if (obj.guardChance !== undefined) baseObj.guardChance = obj.guardChance;
    if (obj.guardValue !== undefined) baseObj.guardValue = obj.guardValue;
    if (obj.guardWeeklyIncrement !== undefined) baseObj.guardWeeklyIncrement = obj.guardWeeklyIncrement;
    if (obj.removeGuardIfHasOwner !== undefined) baseObj.removeGuardIfHasOwner = obj.removeGuardIfHasOwner;
    if (obj.guardRandomization !== undefined) baseObj.guardRandomization = obj.guardRandomization;
    if (obj.isKeyObject !== undefined) baseObj.isKeyObject = obj.isKeyObject;
    if (obj.enableWeeklyUnitIncrement !== undefined) baseObj.enableWeeklyUnitIncrement = obj.enableWeeklyUnitIncrement;
    if (obj.initialUnitIncrement !== undefined) baseObj.initialUnitIncrement = obj.initialUnitIncrement;

    // Placement is emitted only when set (fresh editor objects get explicit
    // defaults at creation time), so imported objects rebuild verbatim.
    if (obj.placement !== undefined) baseObj.placement = obj.placement;
    if (obj.placementArgs !== undefined) baseObj.placementArgs = [...obj.placementArgs];

    if (obj.type === "Spawn") {
      baseObj.spawn = `Player${obj.player || 1}`;
      // Emitted only when set (new editor objects set it explicitly), so
      // imported objects that omit it keep the game default.
      if (obj.buildingsConstructionSid) {
        baseObj.buildingsConstructionSid = obj.buildingsConstructionSid;
      }
      } else if (obj.type === "GladiatorArena") {
        // The arena object is minimal in official templates: no guards, no
        // construction — placement comes from the model like everywhere else.
      } else {
        if (obj.player) {
          baseObj.spawn = `Player${obj.player}`;
        } else {
          delete baseObj.spawn;
        }
        if (obj.owner) {
          baseObj.owner = `Player${obj.owner}`;
        } else {
          delete baseObj.owner;
        }
        if (obj.buildingsConstructionSid) {
          baseObj.buildingsConstructionSid = obj.buildingsConstructionSid;
        }

        if (obj.factionMode === 'spawn' && obj.factionSource) {
          // Keep the original Match rule when it already points at this source
          // (preserves the one-arg same-zone form / the matched index); only
          // synthesise a new one when the source changed or there was none. A
          // same-zone match omits the zone arg, a cross-zone one names it.
          const original = obj.rawFields?.faction as { type?: string; args?: unknown[] } | undefined;
          const originalArgs = Array.isArray(original?.args) ? original!.args : [];
          const originalMatchesSource = original?.type === 'Match' && (
            originalArgs.length >= 2
              ? originalArgs[1] === obj.factionSource
              : originalArgs.length >= 1 && obj.factionSource === zone.id
          );
          if (!originalMatchesSource) {
            baseObj.faction = {
              type: "Match" as const,
              args: obj.factionSource === zone.id ? ["0"] : ["0", obj.factionSource]
            };
          }
          delete baseObj.factions;
        } else if (obj.factionMode === 'specific' && obj.factionId) {
          // The engine reads candidate faction ids from faction.args only —
          // the `factions` array is not part of the C# model and is ignored.
          // Keep the original FromList when it still leads with this id (so a
          // random-from-subset list like ["castle","rampart"] isn't truncated);
          // only synthesise a single-id list when the choice actually changed.
          const original = obj.rawFields?.faction as { type?: string; args?: unknown[] } | undefined;
          const originalArgs = Array.isArray(original?.args) ? original!.args : [];
          const originalMatchesId = original?.type === 'FromList' && originalArgs[0] === obj.factionId;
          if (!originalMatchesId) {
            baseObj.faction = {
              type: "FromList" as const,
              args: [obj.factionId]
            };
          }
          delete baseObj.factions;
        } else if (obj.factionMode === 'random') {
          if (obj.factionFromList && obj.factionFromList.length > 0) {
            // Constrained random: a faction subset or differentFrom exclusions.
            baseObj.faction = { type: "FromList" as const, args: [...obj.factionFromList] };
            delete baseObj.factions;
          } else {
            if (!obj.rawFields?.faction) delete baseObj.faction;
            if (!obj.rawFields?.factions) delete baseObj.factions;
          }
        }

        if (isVictoryCity) {
          baseObj.holdCityWinCon = true;
        } else {
          delete baseObj.holdCityWinCon;
        }
      }
      return baseObj;
  });

  if (rmgMainObjects.length > 0) {
    rmgZone.mainObjects = rmgMainObjects;
    if (zone.roads === undefined && !zone.importedObjects) {
      rmgZone.roads = rmgZone.roads || [];
      rmgZone.roads.unshift({
        type: "Stone",
        from: { type: "MainObject" as const, args: ["0"] },
        to: { type: "Crossroads" as const }
      });
    }
  }
  return rmgZone;
}

function autoGenerateProximityConnections(zones: Zone[], edges: Edge[]): RmgConnection[] {
  const result: RmgConnection[] = [];
  const existingPairs = new Set<string>();
  
  for (const edge of edges) {
    existingPairs.add(`${edge.from}__${edge.to}`);
    existingPairs.add(`${edge.to}__${edge.from}`);
  }
  
  for (let i = 0; i < zones.length; i++) {
    for (let j = i + 1; j < zones.length; j++) {
      const zA = zones[i];
      const zB = zones[j];
      const pairKey = `${zA.id}__${zB.id}`;
      if (existingPairs.has(pairKey)) continue;
      
      const dx = zA.x - zB.x;
      const dy = zA.y - zB.y;
      const dist = Math.sqrt(dx * dx + dy * dy);
      
      if (dist < 0.35) {
        result.push({
          name: `Auto-Grid-${zA.id}-${zB.id}`,
          from: zA.id,
          to: zB.id,
          connectionType: 'Proximity' as const,
          length: dist < 0.22 ? 0.1 : 0.5
        });
      } else if (dist > 0.65) {
        result.push({
          name: `Auto-Repel-${zA.id}-${zB.id}`,
          from: zA.id,
          to: zB.id,
          connectionType: 'Proximity' as const,
          length: 4.0
        });
      }
    }
  }
  return result;
}

export function generateTemplate(
  settings: MapSettings,
  zones: Zone[],
  edges: Edge[],
  objectLibrary: CatalogItem[],
  artifactLists: Record<string, RmgContentListEntry[]>,
  presets: Record<string, Preset>,
  customObjectLists?: Record<string, CustomObjectList>,
  extraVariants?: Array<{
    zones: Zone[];
    edges: Edge[];
    fixedOrientation: boolean;
    orientationAnchor: string;
    preserveLayout: boolean;
    originalOrientation?: RmgOrientation;
    borderWaterWidth: number;
    borderCornerRadius: number;
    originalBorder?: RmgBorder;
  }>
): RmgTemplate {
  // Hero limits
  const max = Math.max(1, Number(settings.heroMax) || 12);
  const heroMin = settings.heroLimitMode === "fixed" ? max : Math.max(1, Number(settings.heroMin) || 1);
  const heroIncrement = settings.heroLimitMode === "fixed" ? 0 : Math.max(0, Number(settings.heroIncrement) || 0);

  // Victory: win conditions are emitted from the independent flags (the source
  // of truth — the engine reads these). The display label is its own field.
  const displayWinCondition = settings.displayWinCondition || "win_condition_1";

  const winConditions: RmgWinConditions = { ...(settings.originalWinConditions || {}) };
  const hadOriginal = (key: string) =>
    Boolean(settings.originalWinConditions && Object.hasOwn(settings.originalWinConditions, key));

  // Flags that default ON in the engine (classic/desertion/heroLighting) must
  // be written explicitly even when off, otherwise the engine re-enables them.
  winConditions.classic = Boolean(settings.classicEnabled);
  winConditions.desertion = Boolean(settings.desertionEnabled);
  winConditions.heroLighting = Boolean(settings.heroLightingEnabled);

  // Flags that default OFF are written only when on, or when the imported
  // template carried them (so an explicit `false` round-trips); a false flag
  // the original never had is dropped rather than invented.
  const setOffFlag = (key: string, value: boolean) => {
    if (value || hadOriginal(key)) winConditions[key] = value;
    else delete winConditions[key];
  };
  setOffFlag('lostStartCity', Boolean(settings.lostStartCityEnabled));
  setOffFlag('cityHold', Boolean(settings.cityHoldEnabled));
  setOffFlag('lostStartHero', Boolean(settings.singleHero));

  // A day/value parameter is written while its parent flag is on. When the flag
  // is off we keep whatever the imported template carried (some official
  // templates leave a dead day with the flag off) and only drop params that
  // were never there. `omitAtDefault` lets a parameter that equals its engine
  // default stay absent when the original didn't carry it — e.g. official
  // immediate-capture templates ship `lostStartCity` with no `lostStartCityDay`
  // (day 0), and we must not invent the key.
  const setParam = (key: string, on: boolean, value: number, omitAtDefault?: number) => {
    if (on) {
      if (omitAtDefault !== undefined && value === omitAtDefault && !hadOriginal(key)) delete winConditions[key];
      else winConditions[key] = value;
    } else if (!hadOriginal(key)) delete winConditions[key];
  };
  setParam('desertionDay', Boolean(settings.desertionEnabled), Number(settings.desertionDay));
  setParam('desertionValue', Boolean(settings.desertionEnabled), Number(settings.desertionValue));
  setParam('heroLightingDay', Boolean(settings.heroLightingEnabled), Number(settings.heroLightingDay));
  setParam('lostStartCityDay', Boolean(settings.lostStartCityEnabled), Number(settings.lostStartCityDay), 0);
  setParam('cityHoldDays', Boolean(settings.cityHoldEnabled), Number(settings.cityHoldDays));

  // Gladiator Arena
  const hasGladiatorArena = settings.gladiatorArenaEnabled || Boolean(
    settings.originalWinConditions &&
    Object.hasOwn(settings.originalWinConditions, 'gladiatorArena')
  );
  if (hasGladiatorArena) {
    winConditions.gladiatorArena = settings.gladiatorArenaEnabled;
    winConditions.gladiatorArenaRegistrationStartWork =
      settings.originalWinConditions &&
      Object.hasOwn(
        settings.originalWinConditions,
        'gladiatorArenaRegistrationStartWork'
      )
        ? settings.originalWinConditions.gladiatorArenaRegistrationStartWork
        : false;
    winConditions.gladiatorArenaRegistrationStartFight = settings.gladiatorArenaRegistrationStartFight;
    if (
      (settings.originalWinConditions &&
        Object.hasOwn(
          settings.originalWinConditions,
          'gladiatorArenaDaysDelayStart'
        )) ||
      settings.gladiatorArenaDaysDelayStart !== 30
    ) {
      winConditions.gladiatorArenaDaysDelayStart = Number(settings.gladiatorArenaDaysDelayStart);
    } else {
      delete winConditions.gladiatorArenaDaysDelayStart;
    }
    winConditions.gladiatorArenaCountDay = Number(settings.gladiatorArenaCountDay);
  } else {
    delete winConditions.gladiatorArena;
    delete winConditions.gladiatorArenaRegistrationStartWork;
    delete winConditions.gladiatorArenaRegistrationStartFight;
    delete winConditions.gladiatorArenaDaysDelayStart;
    delete winConditions.gladiatorArenaCountDay;
  }

  // Tournament
  const hasTournament = settings.tournamentEnabled || Boolean(
    settings.originalWinConditions &&
    Object.hasOwn(settings.originalWinConditions, 'tournament')
  );
  if (hasTournament) {
    winConditions.tournament = settings.tournamentEnabled;
    winConditions.tournamentPointsToWin = Number(settings.tournamentPointsToWin);
    winConditions.tournamentSaveArmy = settings.tournamentSaveArmy;
    winConditions.tournamentDays = settings.tournamentDays;
    winConditions.tournamentAnnounceDays = settings.tournamentAnnounceDays;
  } else {
    delete winConditions.tournament;
    delete winConditions.tournamentPointsToWin;
    delete winConditions.tournamentSaveArmy;
    delete winConditions.tournamentDays;
    delete winConditions.tournamentAnnounceDays;
  }

  // Champion Select Rule
  if (hasGladiatorArena || hasTournament) {
    winConditions.championSelectRule = settings.gladiatorArenaChampionRule || 'StartHero';
  } else {
    delete winConditions.championSelectRule;
  }

  const template: RmgTemplate = {
    name: settings.name || "Visual Template",
    gameMode: settings.singleHeroMode ? "SingleHero" : "Classic",
    description: typeof settings.description === "string" ? settings.description : defaultTemplateDescription,
    displayWinCondition,
    sizeX: Number(settings.sizeX) || 128,
    sizeZ: Number(settings.sizeZ) || 128,
    gameRules: {
      heroCountMin: heroMin,
      heroCountMax: max,
      heroCountIncrement: heroIncrement,
      heroHireBan: Boolean(settings.heroHireBan),
      encounterHoles: Boolean(settings.encounterHoles),
      factionLawsExpModifier: settings.factionLawsExpModifier ?? 1,
      astrologyExpModifier: settings.astrologyExpModifier ?? 1,
      // Merge other properties from original gameRules (bonuses, etc.)
      ...(settings.originalGameRules || {}),
      winConditions
    }
  };

  if (settings.originalRawRootFields) {
    Object.assign(template, settings.originalRawRootFields);
  }

  // Per-object guard overrides; the variant key is kept only when set so
  // the few official entries without it round-trip verbatim.
  if (settings.valueOverrides && settings.valueOverrides.length > 0) {
    template.valueOverrides = settings.valueOverrides.map((override) => ({
      sid: override.sid,
      ...(override.variant !== undefined ? { variant: override.variant } : {}),
      guardValue: override.guardValue
    }));
  }

  // Starting bonuses: always exported as an array (the normal official
  // shape); an empty list is omitted. receiverFilter is skipped when empty so
  // side-wide bonuses match the official entries that omit the key.
  if (settings.startingBonuses && settings.startingBonuses.length > 0) {
    template.gameRules.bonuses = settings.startingBonuses.map((bonus) => ({
      sid: bonus.sid,
      receiverSide: bonus.receiverSide,
      ...(bonus.receiverFilter ? { receiverFilter: bonus.receiverFilter } : {}),
      parameters: [...bonus.parameters]
    }));
  }

  // Global bans (items/spells/heroes) live at the template root; empty lists
  // are omitted entirely, matching the official templates.
  const globalBans: RmgGlobalBans = {};
  if (settings.bannedItems?.length) globalBans.items = settings.bannedItems;
  if (settings.bannedSpells?.length) globalBans.magics = settings.bannedSpells;
  if (settings.bannedHeroes?.length) globalBans.heroes = settings.bannedHeroes;
  if (Object.keys(globalBans).length > 0) {
    template.globalBans = globalBans;
  }
  
  if (!zones.length) return template;

  const rmgZones = zones.map((zone) => toRmgZone(zone, edges, presets, settings));
  const connections: RmgConnection[] = edges.map((edgeData) => {
    // Check the discriminant directly (not via a boolean) so TypeScript
    // narrows connectionType to the non-Proximity union after this branch.
    if (edgeData.connectionType === 'Proximity') {
      const connection: RmgProximityConnection = {
        ...(edgeData.rawFields || {}),
        name: connectionName(edgeData),
        from: edgeData.from,
        to: edgeData.to,
        connectionType: 'Proximity',
        length: edgeData.length ?? 0.1
      };
      if (edgeData.guardValue !== 0) {
        connection.guardValue = Number(edgeData.guardValue);
      }
      return connection;
    }

    const connection: RmgPassageConnection = {
      ...(edgeData.rawFields || {}),
      name: connectionName(edgeData),
      from: edgeData.from,
      to: edgeData.to,
      guardValue: Number(edgeData.guardValue) || 0,
      connectionType: edgeData.connectionType,
      road: edgeData.road
    };
    // Optional guard tuning fields are emitted only when set, so templates
    // that omit them keep the game defaults instead of pinned values.
    if (edgeData.simTurnSquad !== undefined) connection.simTurnSquad = edgeData.simTurnSquad;
    if (edgeData.guardWeeklyIncrement !== undefined) connection.guardWeeklyIncrement = edgeData.guardWeeklyIncrement;
    if (edgeData.guardEscape !== undefined) connection.guardEscape = edgeData.guardEscape;
    if (edgeData.guardRandomization !== undefined) connection.guardRandomization = edgeData.guardRandomization;
    if (edgeData.guardZone !== undefined) connection.guardZone = edgeData.guardZone;
    if (edgeData.gatePlacement !== undefined) connection.gatePlacement = edgeData.gatePlacement;
    if (edgeData.guardMatchGroup !== undefined) connection.guardMatchGroup = edgeData.guardMatchGroup;
    if (edgeData.portalPlacementRulesTo) connection.portalPlacementRulesTo = edgeData.portalPlacementRulesTo.map((r) => ({ ...r }));
    if (edgeData.portalPlacementRulesFrom) connection.portalPlacementRulesFrom = edgeData.portalPlacementRulesFrom.map((r) => ({ ...r }));
    return connection;
  });
  
  if (settings.preserveLayout && settings.originalZoneLayouts === undefined) {
    const autoConnections = autoGenerateProximityConnections(zones, edges);
    connections.push(...autoConnections);
  }
  
  // Border: imported templates keep their original border verbatim; the two
  // editable knobs (water band width, corner rounding) are applied on top.
  const variant: RmgVariant = {
    border: {
      ...defaultBorder(),
      ...(settings.originalBorder || {}),
      waterWidth: Math.max(0, Number(settings.borderWaterWidth) || 0),
      cornerRadius: Math.max(0, Number(settings.borderCornerRadius) || 0)
    },
    zones: rmgZones,
    connections
  };
  
  if (settings.fixedOrientation) {
    const anchorId = orientationAnchorName(settings, zones);
    const anchorZone = zones.find(z => z.id === anchorId);
    let angle = 0;
    if (anchorZone && zones.length > 1) {
      // Calculate center of mass of all zones
      const sumX = zones.reduce((sum, z) => sum + z.x, 0);
      const sumY = zones.reduce((sum, z) => sum + z.y, 0);
      const centerX = sumX / zones.length;
      const centerY = sumY / zones.length;
      
      const dx = centerX - anchorZone.x;
      // Invert Y because SVG coordinates go down while trigonometric coordinates go up
      const dy = anchorZone.y - centerY;
      
      const radians = Math.atan2(dy, dx);
      let degrees = Math.round(radians * (180 / Math.PI));
      if (degrees < 0) degrees += 360;
      angle = degrees;
    }
    
    variant.orientation = {
      zeroAngleZone: anchorId,
      baseAngleMin: angle,
      baseAngleMax: angle,
      randomAngleAmplitude: 0,
      randomAngleStep: 0,
      ...(settings.originalOrientation || {})
    };

    if (
      settings.originalOrientation &&
      !Object.prototype.hasOwnProperty.call(
        settings.originalOrientation,
        "zeroAngleZone"
      ) &&
      !settings.orientationAnchor
    ) {
      delete (variant.orientation as Partial<RmgOrientation>).zeroAngleZone;
    }
  }
  
  // Content pools come from the model. Imported pools are always re-emitted,
  // the editor's custom pools only when referenced; zones without explicit
  // references fall back to the generated visual_pool_* set by zone type.
  const allVariantZones = [zones, ...(extraVariants ?? []).map((extra) => extra.zones)].flat();
  const referencedPools = new Set<string>();
  for (const zone of allVariantZones) {
    for (const ref of [
      ...(zone.guardedContentPool ?? []),
      ...(zone.unguardedContentPool ?? []),
      ...(zone.resourcesContentPool ?? [])
    ]) {
      referencedPools.add(ref);
    }
  }

  const poolGroupToRmg = (entry: ContentPoolGroup): JsonValue =>
    entry.raw !== undefined
      ? entry.raw
      : { weight: entry.weight, includeLists: [...entry.includeLists] };
  const poolBanToRmg = (entry: ContentPoolBan): JsonValue => {
    if (entry.raw !== undefined) return entry.raw;
    const ban: JsonObject = { sid: entry.sid ?? "" };
    if (entry.variant !== undefined) ban.variant = entry.variant;
    return ban;
  };

  const modelPools: RmgContentPool[] = (settings.contentPoolPresets ?? [])
    .filter((pool) => referencedPools.has(pool.name) || !pool.custom)
    .map((pool) => {
      const out: RmgContentPool = {
        ...(pool.rawFields || {}),
        name: pool.name
      } as RmgContentPool;
      if (pool.valueDistribution !== undefined) {
        out.valueDistribution = {
          priceBounds: [...pool.valueDistribution.priceBounds],
          weights: [...pool.valueDistribution.weights]
        };
      }
      out.groups = pool.groups.map(poolGroupToRmg) as RmgContentPoolGroup[];
      out.bans = pool.bans.map(poolBanToRmg) as Array<{ sid: string; variant?: number }>;
      return out;
    });

  // The generated fallback pools, for zones with no explicit references
  // (their names may also be referenced explicitly).
  const modelPoolNames = new Set(modelPools.map((pool) => pool.name));
  const autoPools = buildContentPools(
    allVariantZones.filter((zone) => !zone.guardedContentPool && !zone.unguardedContentPool),
    objectLibrary,
    presets,
    referencedPools
  ).filter((pool) => !modelPoolNames.has(pool.name));

  const contentPools: RmgContentPool[] = [...modelPools, ...autoPools];
  
  template.variants = [variant];
  template.zoneLayouts = defaultZoneLayouts(zones, presets, settings);
  
  function isObjectsListUnchanged(zone: Zone): boolean {
    if (!zone.importedObjects) return false;
    return JSON.stringify(zone.objects) === JSON.stringify(zone.importedObjects);
  }

  // Re-use original mandatoryContent array structure for list names
  const mandatoryContentMap = new Map<string, RmgMandatoryObject[]>();
  zones.forEach((zone) => {
    const listName = (zone.mandatoryContent && zone.mandatoryContent[0]) || `mandatory_content_${safeName(zone.id).toLowerCase()}`;
    const useRaw = zone.rawMandatoryContent && isObjectsListUnchanged(zone);
    const content = (useRaw ? zone.rawMandatoryContent : buildMandatoryObjects(zone)) || [];
    mandatoryContentMap.set(listName, content);
  });

  template.mandatoryContent = Array.from(mandatoryContentMap.entries()).map(([name, content]) => ({
    name,
    content
  }));
  
  // Content-limit presets come from the model. Imported presets are always
  // re-emitted; the editor's own (custom and built-in) presets only when some
  // zone references them — explicitly or through the auto default by type.
  {
    const allZones = [zones, ...(extraVariants ?? []).map((extra) => extra.zones)].flat();
    const referencedLimits = new Set<string>();
    for (const zone of allZones) {
      const refs = zone.contentCountLimits ?? [
        getBaseType(zone.type, presets) === "spawn" || zone.mainObjects?.some((mo) => mo.type === "Spawn")
          ? "content_limits_spawn"
          : "content_limits_side"
      ];
      for (const name of refs) referencedLimits.add(name);
    }

    const limitEntryToRmg = (entry: ContentLimitEntry): JsonValue => {
      if (entry.raw !== undefined) return entry.raw;
      if (entry.includeLists !== undefined) {
        return { includeLists: [...entry.includeLists], maxCount: entry.maxCount };
      }
      const row: JsonObject = { sid: entry.sid ?? "" };
      if (entry.variant !== undefined) row.variant = entry.variant;
      row.maxCount = entry.maxCount;
      return row;
    };

    // Officials reuse the stub names with real rules — only the editor's own
    // factory-shaped (empty) stubs are filtered when unreferenced.
    const isFactoryStub = (preset: NonNullable<MapSettings['contentLimitPresets']>[number]) =>
      isBuiltInLimitName(preset.name) &&
      preset.limits.length === 0 &&
      preset.playerMin === undefined &&
      preset.playerMax === undefined &&
      !preset.rawFields;

    const modelPresets = settings.contentLimitPresets ?? [];
    template.contentCountLimits = modelPresets
      .filter((preset) => referencedLimits.has(preset.name) || (!preset.custom && !isFactoryStub(preset)))
      .map((preset) => {
        const out: RmgContentCountLimit = {
          ...(preset.rawFields || {}),
          name: preset.name,
          limits: []
        };
        if (preset.playerMin !== undefined) out.playerMin = preset.playerMin;
        if (preset.playerMax !== undefined) out.playerMax = preset.playerMax;
        out.limits = preset.limits.map(limitEntryToRmg);
        return out;
      });

    // Auto references may point at the editor stubs even when the model list
    // lost them (e.g. a freshly imported template) — append empty fallbacks.
    for (const stub of ["content_limits_spawn", "content_limits_side"]) {
      if (referencedLimits.has(stub) && !template.contentCountLimits.some((preset) => preset.name === stub)) {
        template.contentCountLimits.push({ name: stub, limits: [] });
      }
    }
  }

  template.contentPools = contentPools;
  
  // Merge original or custom contentLists with generated fallback lists
  let storeLists: RmgContentList[] = [];
  if (customObjectLists && Object.keys(customObjectLists).length > 0) {
    storeLists = Object.values(customObjectLists).map((list) => {
      return {
        name: list.id,
        content: list.entries.map((entry: CustomObjectListEntry) => {
          const item: RmgContentListEntry = {};
          if (entry.kind === 'list') {
            item.includeLists = [entry.value];
          } else {
            item.sid = entry.value;
          }
          item.weight = entry.weight;
          return item;
        })
      };
    });
  } else if (settings.originalContentLists !== undefined) {
    storeLists = settings.originalContentLists;
  }

  // Merge with required generated fallback lists
  const requiredLists = requiredGeneratedContentLists(zones, contentPools || []);
  const generatedLists = buildContentLists(artifactLists, requiredLists);
  
  const mergedLists: RmgContentList[] = [...storeLists];
  generatedLists.forEach(genList => {
    if (!mergedLists.some(l => l.name === genList.name)) {
      mergedLists.push(genList);
    }
  });

  if (mergedLists.length > 0) {
    template.contentLists = mergedLists;
  } else if (settings.originalZoneLayouts !== undefined) {
    // Keep it undefined if it was layouts-only
  }

  // Append additional generation variants. Each is generated by the same logic
  // via a recursive single-variant call; shared per-zone arrays (mandatory
  // content, zone layouts, generated content lists) are merged by name so the
  // extra variants' zones resolve correctly. Orientation is per-variant in the
  // game format, so each extra variant exports its own.
  if (extraVariants && extraVariants.length > 0) {
    for (const extra of extraVariants) {
      const subSettings: MapSettings = {
        ...settings,
        fixedOrientation: extra.fixedOrientation,
        orientationAnchor: extra.orientationAnchor,
        preserveLayout: extra.preserveLayout,
        originalOrientation: extra.originalOrientation,
        borderWaterWidth: extra.borderWaterWidth,
        borderCornerRadius: extra.borderCornerRadius,
        originalBorder: extra.originalBorder
      };
      const sub = generateTemplate(
        subSettings,
        extra.zones,
        extra.edges,
        objectLibrary,
        artifactLists,
        presets,
        customObjectLists
      );
      const subVariant = sub.variants?.[0];
      if (subVariant) {
        (template.variants ??= []).push(subVariant);
      }
      for (const entry of sub.mandatoryContent ?? []) {
        if (!(template.mandatoryContent ?? []).some((existing) => existing.name === entry.name)) {
          (template.mandatoryContent ??= []).push(entry);
        }
      }
      for (const layout of sub.zoneLayouts ?? []) {
        if (!(template.zoneLayouts ?? []).some((existing) => existing.name === layout.name)) {
          (template.zoneLayouts ??= []).push(layout);
        }
      }
      for (const list of sub.contentLists ?? []) {
        if (!(template.contentLists ?? []).some((existing) => existing.name === list.name)) {
          (template.contentLists ??= []).push(list);
        }
      }
    }
  }

  return template;
}
