export const OFFICIAL_TEMPLATE_NAMES = [
  "All Around.rmg.json",
  "Anarchy.rmg.json",
  "Arcade.rmg.json",
  "Blitz.rmg.json",
  "Chosen One.rmg.json",
  "Christmas Tree.rmg.json",
  "Crossroads.rmg.json",
  "Diamond.rmg.json",
  "Exodus Classic.rmg.json",
  "Exodus.rmg.json",
  "Expanse.rmg.json",
  "Eye of the Storm.rmg.json",
  "Fair'n Square.rmg.json",
  "Flashback.rmg.json",
  "Full Hire.rmg.json",
  "Hallway.rmg.json",
  "Hard Place.rmg.json",
  "Harmony.rmg.json",
  "Helltide.rmg.json",
  "Highway.rmg.json",
  "Ikarus.rmg.json",
  "Infinity.rmg.json",
  "Jebus Cross Classic.rmg.json",
  "Jebus Cross.rmg.json",
  "Jebus Outcast.rmg.json",
  "Junction.rmg.json",
  "Kerberos.rmg.json",
  "King of the Hill.rmg.json",
  "Last Fortress.rmg.json",
  "Last Stand.rmg.json",
  "Madness.rmg.json",
  "Maneuvers.rmg.json",
  "Massacre.rmg.json",
  "Maze.rmg.json",
  "Mini-Nostalgia.rmg.json",
  "Miracle.rmg.json",
  "Nuclear.rmg.json",
  "OctoJebus.rmg.json",
  "One for All.rmg.json",
  "Overthrow.rmg.json",
  "Pyramid.rmg.json",
  "Sand Clover.rmg.json",
  "Shamrock.rmg.json",
  "Showdown.rmg.json",
  "Spider.rmg.json",
  "Sprint.rmg.json",
  "Staircase.rmg.json",
  "Sworn.rmg.json",
  "Symmetry.rmg.json",
  "Symphony.rmg.json",
  "Trinity.rmg.json",
  "Universe.rmg.json",
  "Vendetta.rmg.json",
  "Wastelands.rmg.json",
  "Yin Yang.rmg.json",
  "Zookeeper.rmg.json"
] as const;
